// State/UT -> District master data (28 States + 8 UTs). This is the single source
// of truth for the geo hierarchy: seed.ts uses it to generate users/schools, and
// index.ts's /api/states, /districts, /blocks routes read from it directly so the
// coordinator-registration flow always matches what was actually seeded.
export interface DistrictInfo {
  code: string;
  name: string;
}

export interface StateInfo {
  code: string;
  name: string;
  districts: DistrictInfo[];
}

export const STATES_UTS: StateInfo[] = [
  // ── 28 STATES ──
  {
    code: 'AP', name: 'Andhra Pradesh',
    districts: [
      { code: 'ASR_AP', name: 'Alluri Sitharama Raju' },
      { code: 'AKP', name: 'Anakapalli' },
      { code: 'ATP', name: 'Ananthapuramu' },
      { code: 'ANN', name: 'Annamayya' },
      { code: 'BPT', name: 'Bapatla' },
      { code: 'CTR_AP', name: 'Chittoor' },
      { code: 'KNS', name: 'Dr. B.R. Ambedkar Konaseema' },
      { code: 'EGD', name: 'East Godavari' },
      { code: 'ELR', name: 'Eluru' },
      { code: 'GNT', name: 'Guntur' },
      { code: 'KKD_AP', name: 'Kakinada' },
      { code: 'KRI', name: 'Krishna' },
      { code: 'KRN', name: 'Kurnool' },
      { code: 'NDL', name: 'Nandyal' },
      { code: 'NTR', name: 'NTR / Vijayawada' },
      { code: 'PLN', name: 'Palnadu' },
      { code: 'PVM', name: 'Parvathipuram Manyam' },
      { code: 'PRK', name: 'Prakasam' },
      { code: 'NLR', name: 'Sri Potti Sriramulu Nellore' },
      { code: 'SSS', name: 'Sri Sathya Sai' },
      { code: 'SKL', name: 'Srikakulam' },
      { code: 'TPT', name: 'Tirupati' },
      { code: 'VSP', name: 'Visakhapatnam' },
      { code: 'VZM', name: 'Vizianagaram' },
      { code: 'WGD', name: 'West Godavari' },
      { code: 'YSR', name: 'YSR Kadapa' },
    ],
  },
  {
    code: 'AR', name: 'Arunachal Pradesh',
    districts: [
      { code: 'AJW', name: 'Anjaw' },
      { code: 'CHG', name: 'Changlang' },
      { code: 'DBV', name: 'Dibang Valley' },
      { code: 'EKM_AR', name: 'East Kameng' },
      { code: 'ESG', name: 'East Siang' },
      { code: 'KML', name: 'Kamle' },
      { code: 'KRD_AR', name: 'Kra Daadi' },
      { code: 'KRK', name: 'Kurung Kumey' },
      { code: 'LPD', name: 'Leparada' },
      { code: 'LHT', name: 'Lohit' },
      { code: 'LDG', name: 'Longding' },
      { code: 'LDV', name: 'Lower Dibang Valley' },
      { code: 'LWS', name: 'Lower Siang' },
      { code: 'LSS', name: 'Lower Subansiri' },
      { code: 'NMS', name: 'Namsai' },
      { code: 'PKK', name: 'Pakke Kessang' },
      { code: 'PPP', name: 'Papum Pare' },
      { code: 'SYM', name: 'Shi Yomi' },
      { code: 'SNG_AR', name: 'Siang' },
      { code: 'TWG', name: 'Tawang' },
      { code: 'TRP', name: 'Tirap' },
      { code: 'UPS', name: 'Upper Siang' },
      { code: 'USS', name: 'Upper Subansiri' },
      { code: 'WKM', name: 'West Kameng' },
      { code: 'WSG', name: 'West Siang' },
      { code: 'ICC', name: 'Itanagar Capital Complex' },
    ],
  },
  {
    code: 'AS', name: 'Assam',
    districts: [
      { code: 'BJL', name: 'Bajali' },
      { code: 'BKS', name: 'Baksa' },
      { code: 'BRP', name: 'Barpeta' },
      { code: 'BSW_AS', name: 'Biswanath' },
      { code: 'BNG_AS', name: 'Bongaigaon' },
      { code: 'CCH', name: 'Cachar' },
      { code: 'CRD', name: 'Charaideo' },
      { code: 'CRG', name: 'Chirang' },
      { code: 'DRG_AS', name: 'Darrang' },
      { code: 'DMJ', name: 'Dhemaji' },
      { code: 'DHB', name: 'Dhubri' },
      { code: 'DBR', name: 'Dibrugarh' },
      { code: 'DMH_AS', name: 'Dima Hasao' },
      { code: 'GLP', name: 'Goalpara' },
      { code: 'GLT', name: 'Golaghat' },
      { code: 'HLK', name: 'Hailakandi' },
      { code: 'HOJ', name: 'Hojai' },
      { code: 'JRH', name: 'Jorhat' },
      { code: 'KRM', name: 'Kamrup Metropolitan' },
      { code: 'KRR_AS', name: 'Kamrup Rural' },
      { code: 'KBA', name: 'Karbi Anglong' },
      { code: 'KMG', name: 'Karimganj' },
      { code: 'KKR_AS', name: 'Kokrajhar' },
      { code: 'LKP_AS', name: 'Lakhimpur' },
      { code: 'MJL', name: 'Majuli' },
      { code: 'MRG', name: 'Morigaon' },
      { code: 'NGN', name: 'Nagaon' },
      { code: 'NLB', name: 'Nalbari' },
      { code: 'SVS', name: 'Sivasagar' },
      { code: 'SNT', name: 'Sonitpur' },
      { code: 'SSM', name: 'South Salmara-Mankachar' },
      { code: 'TMP', name: 'Tamulpur' },
      { code: 'TSK', name: 'Tinsukia' },
      { code: 'UDL', name: 'Udalguri' },
      { code: 'WKA', name: 'West Karbi Anglong' },
    ],
  },
  {
    code: 'BR', name: 'Bihar',
    districts: [
      { code: 'ARA', name: 'Araria' },
      { code: 'ARW', name: 'Arwal' },
      { code: 'AUR_BR', name: 'Aurangabad' },
      { code: 'BNK', name: 'Banka' },
      { code: 'BGS', name: 'Begusarai' },
      { code: 'BGP_BR', name: 'Bhagalpur' },
      { code: 'BHP', name: 'Bhojpur' },
      { code: 'BXR', name: 'Buxar' },
      { code: 'DBG', name: 'Darbhanga' },
      { code: 'ECM', name: 'East Champaran' },
      { code: 'GAY', name: 'Gaya' },
      { code: 'GPL', name: 'Gopalganj' },
      { code: 'JMU', name: 'Jamui' },
      { code: 'JHD', name: 'Jehanabad' },
      { code: 'KMR_BR', name: 'Kaimur' },
      { code: 'KTR', name: 'Katihar' },
      { code: 'KHG', name: 'Khagaria' },
      { code: 'KSG_BR', name: 'Kishanganj' },
      { code: 'LKS', name: 'Lakhisarai' },
      { code: 'MDP', name: 'Madhepura' },
      { code: 'MDB', name: 'Madhubani' },
      { code: 'MNG', name: 'Munger' },
      { code: 'MUZ', name: 'Muzaffarpur' },
      { code: 'NAL', name: 'Nalanda' },
      { code: 'NWD', name: 'Nawada' },
      { code: 'PAT_BR', name: 'Patna' },
      { code: 'PUR', name: 'Purnia' },
      { code: 'RHT', name: 'Rohtas' },
      { code: 'SHS', name: 'Saharsa' },
      { code: 'SMT', name: 'Samastipur' },
      { code: 'SRN', name: 'Saran' },
      { code: 'SKP', name: 'Sheikhpura' },
      { code: 'SHH', name: 'Sheohar' },
      { code: 'STM', name: 'Sitamarhi' },
      { code: 'SWN', name: 'Siwan' },
      { code: 'SPL', name: 'Supaul' },
      { code: 'VSH', name: 'Vaishali' },
      { code: 'WCM', name: 'West Champaran' },
    ],
  },
  {
    code: 'CG', name: 'Chhattisgarh',
    districts: [
      { code: 'BLD_CG', name: 'Balod' },
      { code: 'BDB', name: 'Baloda Bazar' },
      { code: 'BLR_CG', name: 'Balrampur' },
      { code: 'BST_CG', name: 'Bastar' },
      { code: 'BMT', name: 'Bemetara' },
      { code: 'BJP', name: 'Bijapur' },
      { code: 'BLP_CG', name: 'Bilaspur' },
      { code: 'DTW', name: 'Dantewada / South Bastar' },
      { code: 'DHM', name: 'Dhamtari' },
      { code: 'DRG', name: 'Durg' },
      { code: 'GRB', name: 'Gariaband' },
      { code: 'GPM', name: 'Gaurela-Pendra-Marwahi' },
      { code: 'JJC', name: 'Janjgir-Champa' },
      { code: 'JSP_CG', name: 'Jashpur' },
      { code: 'KBD', name: 'Kabirdham / Kawardha' },
      { code: 'KNK', name: 'Kanker / North Bastar' },
      { code: 'KCG', name: 'Khairagarh-Chhuikhadan-Gandai' },
      { code: 'KDG_CG', name: 'Kondagaon' },
      { code: 'KRB', name: 'Korba' },
      { code: 'KRY', name: 'Koriya' },
      { code: 'MSM', name: 'Mahasamund' },
      { code: 'MCB', name: 'Manendragarh-Chirmiri-Bharatpur' },
      { code: 'MMA', name: 'Mohla-Manpur-Ambagarh Chowki' },
      { code: 'MGL', name: 'Mungeli' },
      { code: 'NRP', name: 'Narayanpur' },
      { code: 'RGH', name: 'Raigarh' },
      { code: 'RPR', name: 'Raipur' },
      { code: 'RJN', name: 'Rajnandgaon' },
      { code: 'SKT', name: 'Sakti' },
      { code: 'SGB', name: 'Sarangarh-Bilaigarh' },
      { code: 'SKM', name: 'Sukma' },
      { code: 'SRJ', name: 'Surajpur' },
      { code: 'SRG', name: 'Surguja' },
    ],
  },
  {
    code: 'GA', name: 'Goa',
    districts: [
      { code: 'NG', name: 'North Goa' },
      { code: 'SG', name: 'South Goa' },
    ],
  },
  {
    code: 'GJ', name: 'Gujarat',
    districts: [
      { code: 'AMD', name: 'Ahmedabad' },
      { code: 'SRT', name: 'Surat' },
    ],
  },
  {
    code: 'HR', name: 'Haryana',
    districts: [
      { code: 'AMB', name: 'Ambala' },
      { code: 'PKL', name: 'Panchkula' },
      { code: 'KRN', name: 'Karnal' },
    ],
  },
  {
    code: 'HP', name: 'Himachal Pradesh',
    districts: [
      { code: 'SHL', name: 'Shimla' },
      { code: 'KNG', name: 'Kangra' },
    ],
  },
  {
    code: 'JH', name: 'Jharkhand',
    districts: [
      { code: 'BKO', name: 'Bokaro' },
      { code: 'CTR', name: 'Chatra' },
      { code: 'DGR', name: 'Deoghar' },
      { code: 'DHN', name: 'Dhanbad' },
      { code: 'DMK', name: 'Dumka' },
      { code: 'ESB', name: 'East Singhbhum' },
      { code: 'GRH', name: 'Garhwa' },
      { code: 'GRD', name: 'Giridih' },
      { code: 'GDD', name: 'Godda' },
      { code: 'GML', name: 'Gumla' },
      { code: 'HZB', name: 'Hazaribagh' },
      { code: 'JMT', name: 'Jamtara' },
      { code: 'KHT_JH', name: 'Khunti' },
      { code: 'KOD', name: 'Koderma' },
      { code: 'LTH', name: 'Latehar' },
      { code: 'LHD', name: 'Lohardaga' },
      { code: 'PKR', name: 'Pakur' },
      { code: 'PLM', name: 'Palamu' },
      { code: 'RMG', name: 'Ramgarh' },
      { code: 'RNC', name: 'Ranchi' },
      { code: 'SBG', name: 'Sahibganj' },
      { code: 'SKR_JH', name: 'Seraikela Kharsawan' },
      { code: 'SMD', name: 'Simdega' },
      { code: 'WSB', name: 'West Singhbhum' },
    ],
  },
  {
    code: 'KA', name: 'Karnataka',
    districts: [
      { code: 'BGK', name: 'Bagalkote' },
      { code: 'BLR_KA', name: 'Ballari' },
      { code: 'BLG_KA', name: 'Belagavi' },
      { code: 'BGR', name: 'Bengaluru Rural' },
      { code: 'BGU', name: 'Bengaluru Urban' },
      { code: 'BDR', name: 'Bidar' },
      { code: 'CRN', name: 'Chamarajanagara' },
      { code: 'CKB', name: 'Chikkaballapura' },
      { code: 'CKM', name: 'Chikkamagaluru' },
      { code: 'CTA', name: 'Chitradurga' },
      { code: 'DKN', name: 'Dakshina Kannada' },
      { code: 'DVG', name: 'Davanagere' },
      { code: 'DHW', name: 'Dharwad' },
      { code: 'GDG', name: 'Gadag' },
      { code: 'HSN', name: 'Hassan' },
      { code: 'HVR', name: 'Haveri' },
      { code: 'KLB', name: 'Kalaburagi' },
      { code: 'KDG', name: 'Kodagu' },
      { code: 'KLR', name: 'Kolar' },
      { code: 'KPL', name: 'Koppal' },
      { code: 'MDY', name: 'Mandya' },
      { code: 'MYS', name: 'Mysuru' },
      { code: 'RCR', name: 'Raichur' },
      { code: 'RMN', name: 'Ramanagara' },
      { code: 'SHM', name: 'Shivamogga' },
      { code: 'TMK', name: 'Tumakuru' },
      { code: 'UDP_KA', name: 'Udupi' },
      { code: 'UKN', name: 'Uttara Kannada' },
      { code: 'VJN', name: 'Vijayanagara' },
      { code: 'VJP', name: 'Vijayapura' },
      { code: 'YDG', name: 'Yadgir' },
    ],
  },
  {
    code: 'KL', name: 'Kerala',
    districts: [
      { code: 'ALP', name: 'Alappuzha' },
      { code: 'EKM', name: 'Ernakulam' },
      { code: 'IDK', name: 'Idukki' },
      { code: 'KNR_KL', name: 'Kannur' },
      { code: 'KSG_KL', name: 'Kasaragod' },
      { code: 'KLM', name: 'Kollam' },
      { code: 'KTM', name: 'Kottayam' },
      { code: 'KKD', name: 'Kozhikode' },
      { code: 'MLP', name: 'Malappuram' },
      { code: 'PLK', name: 'Palakkad' },
      { code: 'PTA', name: 'Pathanamthitta' },
      { code: 'TVM_KL', name: 'Thiruvananthapuram' },
      { code: 'TSR', name: 'Thrissur' },
      { code: 'WYD', name: 'Wayanad' },
    ],
  },
  {
    code: 'MP', name: 'Madhya Pradesh',
    districts: [
      { code: 'BPL', name: 'Bhopal' },
      { code: 'IND', name: 'Indore' },
    ],
  },
  {
    code: 'MH', name: 'Maharashtra',
    districts: [
      { code: 'AHM_MH', name: 'Ahmednagar / Ahilyanagar' },
      { code: 'AKL', name: 'Akola' },
      { code: 'AMR_MH', name: 'Amravati' },
      { code: 'CSN', name: 'Chhatrapati Sambhaji Nagar' },
      { code: 'BED', name: 'Beed' },
      { code: 'BHD_MH', name: 'Bhandara' },
      { code: 'BLD', name: 'Buldhana' },
      { code: 'CHD', name: 'Chandrapur' },
      { code: 'DHL', name: 'Dhule' },
      { code: 'GDC', name: 'Gadchiroli' },
      { code: 'GND_MH', name: 'Gondia' },
      { code: 'HNG', name: 'Hingoli' },
      { code: 'JLG', name: 'Jalgaon' },
      { code: 'JLN_MH', name: 'Jalna' },
      { code: 'KLP_MH', name: 'Kolhapur' },
      { code: 'LTR', name: 'Latur' },
      { code: 'MMC', name: 'Mumbai City' },
      { code: 'MMS', name: 'Mumbai Suburban' },
      { code: 'NGP', name: 'Nagpur' },
      { code: 'NND', name: 'Nanded' },
      { code: 'NDB', name: 'Nandurbar' },
      { code: 'NSK', name: 'Nashik' },
      { code: 'DHR_MH', name: 'Dharashiv / Osmanabad' },
      { code: 'PLG', name: 'Palghar' },
      { code: 'PBN', name: 'Parbhani' },
      { code: 'PUN', name: 'Pune' },
      { code: 'RGD', name: 'Raigad' },
      { code: 'RTN', name: 'Ratnagiri' },
      { code: 'SGL', name: 'Sangli' },
      { code: 'STR', name: 'Satara' },
      { code: 'SND', name: 'Sindhudurg' },
      { code: 'SLP', name: 'Solapur' },
      { code: 'THN', name: 'Thane' },
      { code: 'WRD', name: 'Wardha' },
      { code: 'WSM', name: 'Washim' },
      { code: 'YTL', name: 'Yavatmal' },
    ],
  },
  {
    code: 'MN', name: 'Manipur',
    districts: [
      { code: 'BSP', name: 'Bishnupur' },
      { code: 'CDL', name: 'Chandel' },
      { code: 'CCP', name: 'Churachandpur' },
      { code: 'IE', name: 'Imphal East' },
      { code: 'IW', name: 'Imphal West' },
      { code: 'JRB', name: 'Jiribam' },
      { code: 'KCG_MN', name: 'Kakching' },
      { code: 'KMJ', name: 'Kamjong' },
      { code: 'KPI', name: 'Kangpokpi' },
      { code: 'NNY', name: 'Noney' },
      { code: 'PZL', name: 'Pherzawl' },
      { code: 'SPT', name: 'Senapati' },
      { code: 'TML', name: 'Tamenglong' },
      { code: 'TNP', name: 'Tengnoupal' },
      { code: 'THB', name: 'Thoubal' },
      { code: 'UKR', name: 'Ukhrul' },
    ],
  },
  {
    code: 'ML', name: 'Meghalaya',
    districts: [
      { code: 'EWK', name: 'Eastern West Khasi Hills' },
      { code: 'EGH', name: 'East Garo Hills' },
      { code: 'EJH', name: 'East Jaintia Hills' },
      { code: 'EKH', name: 'East Khasi Hills' },
      { code: 'NGH', name: 'North Garo Hills' },
      { code: 'RBH', name: 'Ri-Bhoi' },
      { code: 'SGH', name: 'South Garo Hills' },
      { code: 'SWG', name: 'South West Garo Hills' },
      { code: 'SWK', name: 'South West Khasi Hills' },
      { code: 'WGH', name: 'West Garo Hills' },
      { code: 'WJH', name: 'West Jaintia Hills' },
      { code: 'WKH', name: 'West Khasi Hills' },
    ],
  },
  {
    code: 'MZ', name: 'Mizoram',
    districts: [
      { code: 'AZL', name: 'Aizawl' },
      { code: 'CMP', name: 'Champhai' },
      { code: 'HNT', name: 'Hnahthial' },
      { code: 'KWZ', name: 'Khawzawl' },
      { code: 'KLB_MZ', name: 'Kolasib' },
      { code: 'LTL', name: 'Lawngtlai' },
      { code: 'LGL', name: 'Lunglei' },
      { code: 'MMT', name: 'Mamit' },
      { code: 'STL', name: 'Saitual' },
      { code: 'SRC', name: 'Serchhip' },
      { code: 'SIH', name: 'Siaha' },
    ],
  },
  {
    code: 'NL', name: 'Nagaland',
    districts: [
      { code: 'CKM_NL', name: 'Chümoukedima' },
      { code: 'DMP', name: 'Dimapur' },
      { code: 'KPH', name: 'Kiphire' },
      { code: 'KHM_NL', name: 'Kohima' },
      { code: 'LLG', name: 'Longleng' },
      { code: 'MKC', name: 'Mokokchung' },
      { code: 'MON', name: 'Mon' },
      { code: 'NLD', name: 'Niuland' },
      { code: 'NKL', name: 'Noklak' },
      { code: 'PRN', name: 'Peren' },
      { code: 'PHK', name: 'Phek' },
      { code: 'SMT_NL', name: 'Shamator' },
      { code: 'TSM', name: 'Tseminyu' },
      { code: 'TSG', name: 'Tuensang' },
      { code: 'WKH_NL', name: 'Wokha' },
      { code: 'ZHB', name: 'Zunheboto' },
    ],
  },
  {
    code: 'OD', name: 'Odisha',
    districts: [
      { code: 'ANG', name: 'Angul' },
      { code: 'BLG_OD', name: 'Balangir' },
      { code: 'BLS_OD', name: 'Balasore' },
      { code: 'BRG', name: 'Bargarh' },
      { code: 'BDK', name: 'Bhadrak' },
      { code: 'BDH', name: 'Boudh' },
      { code: 'CTC', name: 'Cuttack' },
      { code: 'DGH', name: 'Deoghar' },
      { code: 'DNK', name: 'Dhenkanal' },
      { code: 'GJP', name: 'Gajapati' },
      { code: 'GNJ', name: 'Ganjam' },
      { code: 'JSP', name: 'Jagatsinghpur' },
      { code: 'JJP', name: 'Jajpur' },
      { code: 'JSG', name: 'Jharsuguda' },
      { code: 'KLH', name: 'Kalahandi' },
      { code: 'KND', name: 'Kandhamal' },
      { code: 'KNP_OD', name: 'Kendrapara' },
      { code: 'KJR', name: 'Kendujhar / Keonjhar' },
      { code: 'KRD', name: 'Khordha' },
      { code: 'KPT_OD', name: 'Koraput' },
      { code: 'MLK_OD', name: 'Malkangiri' },
      { code: 'MBJ', name: 'Mayurbhanj' },
      { code: 'NBP', name: 'Nabarangpur' },
      { code: 'NYG', name: 'Nayagarh' },
      { code: 'NPD', name: 'Nuapada' },
      { code: 'PRI', name: 'Puri' },
      { code: 'RYG', name: 'Rayagada' },
      { code: 'SBP', name: 'Sambalpur' },
      { code: 'SBP_OD', name: 'Subarnapur / Sonepur' },
      { code: 'SNG_OD', name: 'Sundargarh' },
    ],
  },
  {
    code: 'PB', name: 'Punjab',
    districts: [
      { code: 'ASR', name: 'Amritsar' },
      { code: 'BNL', name: 'Barnala' },
      { code: 'BTH', name: 'Bathinda' },
      { code: 'FDK', name: 'Faridkot' },
      { code: 'FGS', name: 'Fatehgarh Sahib' },
      { code: 'FZK', name: 'Fazilka' },
      { code: 'FZP', name: 'Ferozepur' },
      { code: 'GSP', name: 'Gurdaspur' },
      { code: 'HSP', name: 'Hoshiarpur' },
      { code: 'JAL', name: 'Jalandhar' },
      { code: 'KPT', name: 'Kapurthala' },
      { code: 'LDH', name: 'Ludhiana' },
      { code: 'MLK', name: 'Malerkotla' },
      { code: 'MNS', name: 'Mansa' },
      { code: 'MOG', name: 'Moga' },
      { code: 'PTK', name: 'Pathankot' },
      { code: 'PAT', name: 'Patiala' },
      { code: 'RUP', name: 'Rupnagar' },
      { code: 'SAS', name: 'SAS Nagar (Mohali)' },
      { code: 'SBS', name: 'SBS Nagar (Nawanshahr)' },
      { code: 'MKS', name: 'Sri Muktsar Sahib' },
      { code: 'SNG', name: 'Sangrur' },
      { code: 'TTN', name: 'Tarn Taran' },
    ],
  },
  {
    code: 'RJ', name: 'Rajasthan',
    districts: [
      { code: 'JAI', name: 'Jaipur' },
      { code: 'JDP', name: 'Jodhpur' },
      { code: 'UDA', name: 'Udaipur' },
      { code: 'AJM', name: 'Ajmer' },
    ],
  },
  {
    code: 'SK', name: 'Sikkim',
    districts: [
      { code: 'GTK', name: 'Gangtok' },
      { code: 'GYL', name: 'Gyalshing' },
      { code: 'MGN', name: 'Mangan' },
      { code: 'NMC_SK', name: 'Namchi' },
      { code: 'PKY', name: 'Pakyong' },
      { code: 'SRG_SK', name: 'Soreng' },
    ],
  },
  {
    code: 'TN', name: 'Tamil Nadu',
    districts: [
      { code: 'ARI', name: 'Ariyalur' },
      { code: 'CGP', name: 'Chengalpattu' },
      { code: 'CHN', name: 'Chennai' },
      { code: 'CBE', name: 'Coimbatore' },
      { code: 'CUD', name: 'Cuddalore' },
      { code: 'DPI', name: 'Dharmapuri' },
      { code: 'DGL', name: 'Dindigul' },
      { code: 'ERD', name: 'Erode' },
      { code: 'KLK', name: 'Kallakurichi' },
      { code: 'KCP', name: 'Kancheepuram' },
      { code: 'KKM', name: 'Kanniyakumari' },
      { code: 'KRR', name: 'Karur' },
      { code: 'KGI', name: 'Krishnagiri' },
      { code: 'MDU', name: 'Madurai' },
      { code: 'MYD', name: 'Mayiladuthurai' },
      { code: 'NGP_TN', name: 'Nagapattinam' },
      { code: 'NMK', name: 'Namakkal' },
      { code: 'PBL', name: 'Perambalur' },
      { code: 'PDK', name: 'Pudukkottai' },
      { code: 'RMD', name: 'Ramanathapuram' },
      { code: 'RPT', name: 'Ranipet' },
      { code: 'SLM', name: 'Salem' },
      { code: 'SVG', name: 'Sivaganga' },
      { code: 'TKS', name: 'Tenkasi' },
      { code: 'TNJ', name: 'Thanjavur' },
      { code: 'NLG', name: 'The Nilgiris' },
      { code: 'THN_TN', name: 'Theni' },
      { code: 'TLR', name: 'Thiruvallur' },
      { code: 'TVR', name: 'Thiruvarur' },
      { code: 'TUT', name: 'Thoothukudi / Tuticorin' },
      { code: 'TRI', name: 'Tiruchirappalli' },
      { code: 'TNV', name: 'Tirunelveli' },
      { code: 'TPR_TN', name: 'Tirupathur' },
      { code: 'TPR', name: 'Tiruppur' },
      { code: 'TVM_TN', name: 'Tiruvannamalai' },
      { code: 'VEL', name: 'Vellore' },
      { code: 'VLP', name: 'Viluppuram' },
      { code: 'VRD', name: 'Virudhunagar' },
    ],
  },
  {
    code: 'TS', name: 'Telangana',
    districts: [
      { code: 'ADB', name: 'Adilabad' },
      { code: 'BDK_TS', name: 'Bhadradri Kothagudem' },
      { code: 'HNK', name: 'Hanamkonda' },
      { code: 'HYD', name: 'Hyderabad' },
      { code: 'JGT', name: 'Jagtial' },
      { code: 'JNG', name: 'Jangaon' },
      { code: 'JSB', name: 'Jayashankar Bhupalpally' },
      { code: 'JGL', name: 'Jogulamba Gadwal' },
      { code: 'KMR_TS', name: 'Kamareddy' },
      { code: 'KRM_TS', name: 'Karimnagar' },
      { code: 'KHM', name: 'Khammam' },
      { code: 'KBA_TS', name: 'Kumuram Bheem Asifabad' },
      { code: 'MHBD', name: 'Mahabubabad' },
      { code: 'MBN', name: 'Mahabubnagar' },
      { code: 'MCL', name: 'Mancherial' },
      { code: 'MDK', name: 'Medak' },
      { code: 'MDM', name: 'Medchal-Malkajgiri' },
      { code: 'MLG', name: 'Mulugu' },
      { code: 'NGK', name: 'Nagarkurnool' },
      { code: 'NLG_TS', name: 'Nalgonda' },
      { code: 'NPT', name: 'Narayanpet' },
      { code: 'NRM_TS', name: 'Nirmal' },
      { code: 'NZB', name: 'Nizamabad' },
      { code: 'PDL', name: 'Peddapalli' },
      { code: 'RSC', name: 'Rajanna Sircilla' },
      { code: 'RRD', name: 'Ranga Reddy' },
      { code: 'SGR_TS', name: 'Sangareddy' },
      { code: 'SDP', name: 'Siddipet' },
      { code: 'SRY', name: 'Suryapet' },
      { code: 'VKB', name: 'Vikarabad' },
      { code: 'WNP', name: 'Wanaparthy' },
      { code: 'WRG', name: 'Warangal' },
      { code: 'YDB', name: 'Yadadri Bhuvanagiri' },
    ],
  },
  {
    code: 'TR', name: 'Tripura',
    districts: [
      { code: 'DHL_TR', name: 'Dhalai' },
      { code: 'GMT', name: 'Gomati' },
      { code: 'KHW', name: 'Khowai' },
      { code: 'NTR_TR', name: 'North Tripura' },
      { code: 'SPH', name: 'Sepahijala' },
      { code: 'STR_TR', name: 'South Tripura' },
      { code: 'UNK', name: 'Unakoti' },
      { code: 'WTR', name: 'West Tripura' },
    ],
  },
  {
    code: 'UK', name: 'Uttarakhand',
    districts: [
      { code: 'DDN', name: 'Dehradun' },
      { code: 'HRW', name: 'Haridwar' },
    ],
  },
  {
    code: 'UP', name: 'Uttar Pradesh',
    districts: [
      { code: 'LKO', name: 'Lucknow' },
      { code: 'KNP', name: 'Kanpur' },
      { code: 'VAR', name: 'Varanasi' },
    ],
  },
  {
    code: 'WB', name: 'West Bengal',
    districts: [
      { code: 'KOL', name: 'Kolkata' },
      { code: 'HWH', name: 'Howrah' },
    ],
  },
  // ── 8 UNION TERRITORIES ──
  {
    code: 'AN', name: 'Andaman and Nicobar Islands',
    districts: [
      { code: 'NIC', name: 'Nicobars' },
      { code: 'NMA', name: 'North and Middle Andaman' },
      { code: 'SAN', name: 'South Andaman' },
    ],
  },
  {
    code: 'CH', name: 'Chandigarh',
    districts: [
      { code: 'CHD_UT', name: 'Chandigarh' },
    ],
  },
  {
    code: 'DN', name: 'Dadra and Nagar Haveli and Daman and Diu',
    districts: [
      { code: 'DNH', name: 'Dadra and Nagar Haveli' },
      { code: 'DMN', name: 'Daman' },
      { code: 'DIU', name: 'Diu' },
    ],
  },
  {
    code: 'DL', name: 'Delhi',
    districts: [
      { code: 'CDL_DL', name: 'Central Delhi' },
      { code: 'EDL', name: 'East Delhi' },
      { code: 'NDL_DL', name: 'New Delhi' },
      { code: 'NDL_NORTH', name: 'North Delhi' },
      { code: 'NED', name: 'North East Delhi' },
      { code: 'NWD_DL', name: 'North West Delhi' },
      { code: 'SHD_DL', name: 'Shahdara' },
      { code: 'SDL', name: 'South Delhi' },
      { code: 'SED', name: 'South East Delhi' },
      { code: 'SWD', name: 'South West Delhi' },
      { code: 'WDL', name: 'West Delhi' },
    ],
  },
  {
    code: 'JK', name: 'Jammu and Kashmir',
    districts: [
      { code: 'ANT', name: 'Anantnag' },
      { code: 'BND_JK', name: 'Bandipora' },
      { code: 'BRM', name: 'Baramulla' },
      { code: 'BDG', name: 'Budgam' },
      { code: 'DOD', name: 'Doda' },
      { code: 'GBL', name: 'Ganderbal' },
      { code: 'JMU_JK', name: 'Jammu' },
      { code: 'KTH', name: 'Kathua' },
      { code: 'KST', name: 'Kishtwar' },
      { code: 'KLG', name: 'Kulgam' },
      { code: 'KPW', name: 'Kupwara' },
      { code: 'PCH', name: 'Poonch' },
      { code: 'PLW_JK', name: 'Pulwama' },
      { code: 'RJR', name: 'Rajouri' },
      { code: 'RBN', name: 'Ramban' },
      { code: 'RSI', name: 'Reasi' },
      { code: 'SMB_JK', name: 'Samba' },
      { code: 'SHP_JK', name: 'Shopian' },
      { code: 'SRN_JK', name: 'Srinagar' },
      { code: 'UDH', name: 'Udhampur' },
    ],
  },
  {
    code: 'LA', name: 'Ladakh',
    districts: [
      { code: 'LEH', name: 'Leh' },
      { code: 'KGL', name: 'Kargil' },
    ],
  },
  {
    code: 'LD', name: 'Lakshadweep',
    districts: [
      { code: 'LKD', name: 'Lakshadweep' },
    ],
  },
  {
    code: 'PY', name: 'Puducherry',
    districts: [
      { code: 'PDY', name: 'Puducherry' },
      { code: 'KRK_PY', name: 'Karaikal' },
      { code: 'MAH', name: 'Mahe' },
      { code: 'YAN', name: 'Yanam' },
    ],
  },
];

/**
 * Auto-resolves state & district names to official codes (e.g. Punjab -> PB, Howrah -> HWH)
 */
export function getGeoLookup(stateInput?: string, districtInput?: string) {
  let matchedState: StateInfo | undefined;
  let matchedDistrict: DistrictInfo | undefined;

  const sClean = stateInput?.trim().toLowerCase();
  const dClean = districtInput?.trim().toLowerCase();

  if (sClean) {
    matchedState = STATES_UTS.find(
      s => s.code.toLowerCase() === sClean || s.name.toLowerCase() === sClean
    );
  }

  if (dClean) {
    // If state is matched, prioritize districts within that state
    const targetStates = matchedState ? [matchedState] : STATES_UTS;
    for (const st of targetStates) {
      const found = st.districts.find(
        d =>
          d.code.toLowerCase() === dClean ||
          d.name.toLowerCase() === dClean ||
          (dClean === 'hwr' && d.code === 'HWH') // alias support
      );
      if (found) {
        matchedDistrict = found;
        if (!matchedState) matchedState = st;
        break;
      }
    }
  }

  return {
    stateCode: matchedState?.code || null,
    stateName: matchedState?.name || null,
    districtCode: matchedDistrict?.code || null,
    districtName: matchedDistrict?.name || null,
  };
}

