import { Question } from '../db';
import { getLevelForConcept, getConceptForLevel } from '../config/curriculumMap';

function randomVal(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

/**
 * Concept-driven Question Generator.
 * Generates questions indexed by immutable Concept ID (S1.1 - S7.18).
 * If the level order changes in the curriculum map, questions generated by conceptId remain intact.
 */
export function generateQuestionsByConcept(conceptId: string, subLevel: number = 0): Question[] {
  const questions: Question[] = [];
  const conceptConfig = getLevelForConcept(conceptId);

  const currentLevelNumber = conceptConfig ? conceptConfig.levelNumber : 1;
  const strand = conceptConfig ? conceptConfig.strand : 'Number Sense';
  const subtopic = subLevel === 2 ? 'Remedial' : subLevel === 1 ? 'Easier' : 'Mastery';

  for (let qIdx = 1; qIdx <= 4; qIdx++) {
    const questionId = `${conceptId}_L${currentLevelNumber}.${subLevel}_Q${qIdx}`;
    let questionText = '';
    let answerText = '';
    let type: 'number' | 'text' | 'choice' = 'number';
    let choices: string[] | undefined = undefined;
    let svgAsset: string | undefined = undefined;

    switch (conceptId) {
      // --- Stage 1: Preschool 1 (S1.1 - S1.7) ---
      case 'S1.1': // One-to-One Correspondence
        questionText = `Group A has ${qIdx + 2} cups and Group B has ${qIdx + 2} saucers. Does every cup have a saucer? (Write Yes or No)`;
        answerText = 'yes';
        type = 'choice';
        choices = ['yes', 'no'];
        svgAsset = 'objects';
        break;

      case 'S1.2': // Single Property Classification
        questionText = `Which item belongs to the RED group? (Option A: Red Apple, Option B: Blue Ball)`;
        answerText = 'A';
        type = 'choice';
        choices = ['A', 'B'];
        break;

      case 'S1.3': // Perceptual Same/Different
        questionText = `Do both sets look SAME or DIFFERENT? Set 1: [***], Set 2: [***] (Write Same or Different)`;
        answerText = 'same';
        type = 'choice';
        choices = ['same', 'different'];
        break;

      case 'S1.4': // Rote Verbal Counting to 10
        questionText = `What number comes after ${qIdx + 1} when counting 1 to 10?`;
        answerText = String(qIdx + 2);
        type = 'number';
        break;

      case 'S1.5': // Counting Small Sets (1-3)
        questionText = `Count the objects: [* * *]. How many stars are there?`;
        answerText = '3';
        type = 'number';
        break;

      case 'S1.6': // Shape Matching
        questionText = `Which shape matches the Circle? (Option A: Circle, Option B: Triangle)`;
        answerText = 'A';
        type = 'choice';
        choices = ['A', 'B'];
        break;

      case 'S1.7': // Perceptual Subitizing
        questionText = `Without counting one by one, how many dots are shown? [• •]`;
        answerText = '2';
        type = 'number';
        break;

      // --- Stage 2: Preschool 2 (S2.1 - S2.10) ---
      case 'S2.1': // Quantity Comparison
        {
          const a = randomVal(4, 7);
          const b = randomVal(1, 3);
          questionText = `Set A has ${a} balls. Set B has ${b} balls. Which set has MORE? (Write A or B)`;
          answerText = 'A';
          type = 'choice';
          choices = ['A', 'B'];
        }
        break;

      case 'S2.4': // Counting to 5 (Cardinality)
        questionText = `Count the apples: 🍎 🍎 🍎 🍎. What is the total count?`;
        answerText = '4';
        type = 'number';
        break;

      case 'S2.10': // Basic Shape Composition
        questionText = `Combining 2 triangles together side-by-side forms which composite shape? (Option A: Square/Diamond, Option B: Circle)`;
        answerText = 'A';
        type = 'choice';
        choices = ['A', 'B'];
        break;

      // --- Stage 3: Balvatika (S3.1 - S3.10) ---
      case 'S3.1': // Numeral Recognition
        questionText = `Identify the numeral for seven: (Write in digits)`;
        answerText = '7';
        type = 'number';
        break;

      case 'S3.3': // Object-Mediated Numeral Comparison
        questionText = `Box A (Numeral 8 with 8 stars) vs Box B (Numeral 5 with 5 stars). Which is GREATER? (Write A or B)`;
        answerText = 'A';
        type = 'choice';
        choices = ['A', 'B'];
        break;

      case 'S3.6': // Numeral Sequencing
        questionText = `Complete the sequence: 5, 6, __, 8`;
        answerText = '7';
        type = 'number';
        break;

      // --- Stage 4: Class 1 (S4.1 - S4.15) ---
      case 'S4.1': // Abstract Numeral Comparison
        {
          const n1 = randomVal(6, 9);
          const n2 = randomVal(2, 5);
          questionText = `Which number is larger: ${n1} or ${n2}?`;
          answerText = String(Math.max(n1, n2));
          type = 'number';
        }
        break;

      case 'S4.6': // Single-Digit Addition
        {
          const a = randomVal(2, 5);
          const b = randomVal(1, 4);
          questionText = `Solve: ${a} + ${b} = ____`;
          answerText = String(a + b);
          type = 'number';
        }
        break;

      case 'S4.7': // Single-Digit Subtraction
        {
          const a = randomVal(5, 9);
          const b = randomVal(1, 4);
          questionText = `Solve: ${a} - ${b} = ____`;
          answerText = String(a - b);
          type = 'number';
        }
        break;

      // --- Stage 5: Class 2 (S5.1 - S5.19) ---
      case 'S5.4': // 2-Digit Addition with Regrouping
        {
          const a = randomVal(25, 48);
          const b = randomVal(15, 38);
          questionText = `Solve: ${a} + ${b} = ____`;
          answerText = String(a + b);
          type = 'number';
        }
        break;

      case 'S5.5': // 2-Digit Subtraction with Regrouping
        {
          const a = randomVal(52, 85);
          const b = randomVal(18, 39);
          questionText = `Solve: ${a} - ${b} = ____`;
          answerText = String(a - b);
          type = 'number';
        }
        break;

      // --- Stage 6: Class 3 (S6.1 - S6.14) ---
      case 'S6.6': // Multiplication Fact Fluency
        {
          const a = randomVal(3, 9);
          const b = randomVal(3, 9);
          questionText = `Solve: ${a} × ${b} = ____`;
          answerText = String(a * b);
          type = 'number';
        }
        break;

      case 'S6.7': // Division Facts
        {
          const divisor = randomVal(2, 9);
          const ans = randomVal(2, 9);
          const dividend = divisor * ans;
          questionText = `Solve: ${dividend} ÷ ${divisor} = ____`;
          answerText = String(ans);
          type = 'number';
        }
        break;

      // --- Stage 7: Class 4 (S7.1 - S7.18) ---
      case 'S7.14': // Factors & Multiples
        questionText = `Find the smallest non-zero multiple of 6:`;
        answerText = '6';
        type = 'number';
        break;

      case 'S7.15': // Decimals Intro
        questionText = `Write 3/10 as a decimal:`;
        answerText = '0.3';
        type = 'text';
        break;

      case 'S7.18': // Perimeter & Area
        {
          const l = randomVal(4, 9);
          const w = randomVal(2, 5);
          questionText = `A rectangle has length ${l} cm and width ${w} cm. What is its Area in sq cm?`;
          answerText = String(l * w);
          type = 'number';
        }
        break;

      default:
        // Generic fallback generator for remaining nodes
        questionText = `[Concept ${conceptId}] Level ${currentLevelNumber} Practice Question #${qIdx}`;
        answerText = String(qIdx * 10);
        type = 'number';
        break;
    }

    questions.push({
      question_id: `${conceptId}_Q${qIdx}`,
      question: questionText,
      answer: answerText,
      answer_type: type,
      choices,
      topic: strand,
      subtopic,
      difficulty: subLevel === 2 ? 'easy' : subLevel === 1 ? 'medium' : 'hard',
      source_level: currentLevelNumber,
      conceptId: conceptId,
      svgAsset
    });
  }

  return questions;
}
