// Generates the curriculum summary shown on the public landing page.
//
// The landing page states the *shape* of the framework (how many concepts, how
// many stages, which strands) but never lists the levels themselves. Those
// numbers move: the framework is revised as curriculum research lands, and
// PR #517 alone changed every level number below stage 3. Hand-written copy
// would silently go stale the first time that happens, so the counts are
// derived from backend/src/config/curriculumMap.ts — the same file the rest of
// the system treats as the source of truth — and regenerated on every build.
//
// Only aggregates are emitted. Per-level content readiness (which levels have
// questions built and which do not) is deliberately NOT part of this file: it
// is operational detail, and the landing page is public.
//
// Usage: npx tsx scripts/build-curriculum-summary.ts
// Runs automatically as the frontend's prebuild step.

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { CURRICULUM_MAPPING } from '../backend/src/config/curriculumMap.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'frontend', 'src', 'data', 'curriculumSummary.json');

/** Concept counts are bucketed into four bands for the landing page heat map. */
export const MATRIX_BANDS = [2, 4, 6, Infinity];

/** Lowest and highest age appearing in any "3-4"-style ageGroup band. */
function ageRange(bands: string[]): { min: number; max: number } {
  const ages = bands.flatMap((b) => b.split('-').map(Number)).filter(Number.isFinite);
  return { min: Math.min(...ages), max: Math.max(...ages) };
}

function main() {
  const levels = Object.values(CURRICULUM_MAPPING);
  if (levels.length === 0) {
    console.error('CURRICULUM_MAPPING is empty — refusing to write an empty summary.');
    process.exit(1);
  }

  const strandCounts = new Map<string, number>();
  const stageAges = new Map<number, Set<string>>();
  for (const level of levels) {
    strandCounts.set(level.strand, (strandCounts.get(level.strand) ?? 0) + 1);
    if (!stageAges.has(level.stage)) stageAges.set(level.stage, new Set());
    stageAges.get(level.stage)!.add(level.ageGroup);
  }

  const { min, max } = ageRange(levels.map((l) => l.ageGroup));

  // Stage columns, ascending, labelled by the age band they cover.
  const stageNumbers = [...stageAges.keys()].sort((a, b) => a - b);
  const stages = stageNumbers.map((stage) => ({
    stage,
    ageLabel: [...stageAges.get(stage)!].sort().join(', ').replace(/-/g, '\u2013'),
    count: levels.filter((l) => l.stage === stage).length,
  }));

  // Strand rows x stage columns. Ordered so the staircase reads: a strand that
  // enters earlier sits higher, and among strands entering together the one
  // that retires earlier comes first. That ordering is what makes the shape
  // legible — Pre-Number Foundations stopping at stage 3 while Number Sense
  // runs the whole way is the single most informative thing in the picture.
  const strandNames = [...strandCounts.keys()];
  const rowOf = (strand: string) => stageNumbers.map((stage) =>
    levels.filter((l) => l.strand === strand && l.stage === stage).length);

  const matrix = strandNames
    .map((strand) => {
      const counts = rowOf(strand);
      const present = counts.map((c, i) => (c > 0 ? i : -1)).filter((i) => i >= 0);
      return {
        strand,
        counts,
        total: strandCounts.get(strand)!,
        firstStage: stageNumbers[present[0]],
        lastStage: stageNumbers[present[present.length - 1]],
      };
    })
    .sort((a, b) =>
      a.firstStage - b.firstStage ||
      a.lastStage - b.lastStage ||
      b.total - a.total ||
      a.strand.localeCompare(b.strand))
    .map(({ strand, counts, total }) => ({ strand, counts, total }));

  const summary = {
    // Regenerated by scripts/build-curriculum-summary.ts — do not edit by hand.
    totalConcepts: levels.length,
    totalStages: stageAges.size,
    totalStrands: strandCounts.size,
    ageMin: min,
    ageMax: max,
    maxCellCount: Math.max(...strandNames.flatMap((strand) => rowOf(strand))),
    stages,
    matrix,
  };

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, JSON.stringify(summary, null, 2) + '\n');
  console.log(
    `[curriculum-summary] ${summary.totalConcepts} concepts, ${summary.totalStages} stages, ` +
      `${summary.totalStrands} strands (ages ${min}-${max}) -> ${path.relative(ROOT, OUT)}`
  );
}

main();
