// Produces a DRAFT 59 -> 93 crosswalk for the pedagogy team to review.
//
//   npx tsx scripts/propose-59-to-93-crosswalk.ts
//     -> writes Research/fln_59_to_93_crosswalk.PROPOSED.md   (review this)
//     -> writes Research/fln_59_to_93_crosswalk.PROPOSED.json  (mechanical draft)
//
// This script does NOT decide the mapping. It matches the 59 worksheet-engine
// level titles against the 93-level capability names by token overlap and ranks
// candidates, so the reviewer starts from "check these 59 suggestions" instead
// of "author 59 mappings from a blank page".
//
// Title similarity is not curriculum equivalence. Two decisions the reviewer
// must make and this script deliberately will not:
//   - where one old level splits across two 93-levels, which one owns the content
//   - where an old level has no 93 home, whether the content retires or the
//     93 taxonomy has a genuine gap
//
// The reviewed output must be saved as `fln_59_to_93_crosswalk.json` (no
// PROPOSED suffix) before `npm run seed:levels` will consume it. That rename is
// the human sign-off, and it is intentional friction.

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

const ENGINE = path.join(ROOT, 'frontend', 'public', 'worksheets', 'levels_main.html');
const SKILL_MAP = path.join(ROOT, 'frontend', 'src', 'data', 'skillProgressionMap.ts');
const OUT_MD = path.join(ROOT, 'Research', 'fln_59_to_93_crosswalk.PROPOSED.md');
const OUT_JSON = path.join(ROOT, 'Research', 'fln_59_to_93_crosswalk.PROPOSED.json');

const STOP = new Set(['the', 'a', 'an', 'and', 'or', 'of', 'to', 'in', 'by', 'with', 'through', 'for']);

function tokens(s: string): Set<string> {
  return new Set(
    s.toLowerCase()
      .replace(/[^a-z0-9\s-]/g, ' ')
      .split(/[\s-]+/)
      .filter(t => t.length > 2 && !STOP.has(t))
  );
}

/** Jaccard overlap. Crude on purpose — this is a shortlist, not a verdict. */
function similarity(a: Set<string>, b: Set<string>): number {
  if (!a.size || !b.size) return 0;
  let shared = 0;
  for (const t of a) if (b.has(t)) shared++;
  return shared / (a.size + b.size - shared);
}

async function main() {
  const html = fs.readFileSync(ENGINE, 'utf8');
  const legacy: Array<{ id: number; title: string }> = [];
  for (const m of html.matchAll(/^\{id:(\d+),title:"([^"]*)"/gm)) {
    legacy.push({ id: parseInt(m[1], 10), title: m[2] });
  }

  const { LEVEL_SKILL_MAP } = await import(SKILL_MAP);
  const targets = (LEVEL_SKILL_MAP as any[]).map(l => ({
    levelNumber: l.levelNumber,
    capability: l.capability,
    stage: l.stage,
    sCode: l.sCode,
    tok: tokens(l.capability),
  }));

  const rows = legacy.map(old => {
    const ot = tokens(old.title);
    const ranked = targets
      .map(t => ({ ...t, score: similarity(ot, t.tok) }))
      .sort((a, b) => b.score - a.score)
      .slice(0, 3);
    return { old, ranked };
  });

  const strong = rows.filter(r => r.ranked[0].score >= 0.5).length;
  const weak = rows.filter(r => r.ranked[0].score > 0 && r.ranked[0].score < 0.5).length;
  const none = rows.filter(r => r.ranked[0].score === 0).length;

  // --- Markdown for humans -------------------------------------------------
  const md: string[] = [];
  md.push('# DRAFT — 59 → 93 level crosswalk (proposed, NOT authoritative)');
  md.push('');
  md.push('Generated by `scripts/propose-59-to-93-crosswalk.ts`. **Every row needs review.**');
  md.push('Title similarity is not curriculum equivalence — the confidence column reflects');
  md.push('word overlap between level names and nothing more.');
  md.push('');
  md.push(`- ${legacy.length} legacy levels to place`);
  md.push(`- ${strong} with a strong single candidate (overlap ≥ 0.5)`);
  md.push(`- ${weak} with only a weak candidate — most likely to be wrong`);
  md.push(`- ${none} with no lexical match at all — decide manually`);
  md.push('');
  md.push('## Decisions this file cannot make');
  md.push('');
  md.push('1. **Splits.** Where one legacy level corresponds to two 93-levels, which one');
  md.push('   inherits the worksheet content — or does it go to both?');
  md.push('2. **Orphans.** Where a legacy level has no 93 home, is the content retired, or');
  md.push('   does its absence indicate a real gap in the 93 taxonomy?');
  md.push('');
  md.push('## Proposed mapping');
  md.push('');
  md.push('| Legacy | Legacy title | → | Proposed | Capability | Stage | Overlap | Alternates |');
  md.push('|---|---|---|---|---|---|---|---|');
  for (const { old, ranked } of rows) {
    const best = ranked[0];
    const flag = best.score >= 0.5 ? '' : best.score > 0 ? ' ⚠' : ' ❓';
    const alts = ranked.slice(1).filter(r => r.score > 0)
      .map(r => `L${r.levelNumber} (${r.score.toFixed(2)})`).join(', ') || '—';
    const proposed = best.score > 0 ? `L${best.levelNumber}` : '**?**';
    md.push(
      `| ${old.id} | ${old.title} | → | ${proposed}${flag} | ${best.score > 0 ? best.capability : '—'} | ` +
      `${best.score > 0 ? best.stage : '—'} | ${best.score.toFixed(2)} | ${alts} |`
    );
  }
  md.push('');
  md.push('## Sign-off');
  md.push('');
  md.push('When reviewed, save the corrected mapping as `Research/fln_59_to_93_crosswalk.json`');
  md.push('in the shape `{ "legacy59_to_level": { "1": 4, "2": 7, ... } }`. Omit any legacy');
  md.push('level that should not carry forward. `npm run seed:levels` reads that file only.');
  md.push('');

  fs.writeFileSync(OUT_MD, md.join('\n'));

  // --- JSON starting point -------------------------------------------------
  const draft: Record<string, number> = {};
  for (const { old, ranked } of rows) {
    if (ranked[0].score >= 0.5) draft[String(old.id)] = ranked[0].levelNumber;
  }
  fs.writeFileSync(OUT_JSON, JSON.stringify({
    _warning: 'DRAFT — mechanically proposed, not reviewed. Rename to fln_59_to_93_crosswalk.json only after pedagogy sign-off.',
    _onlyIncludes: 'legacy levels whose best lexical match scored >= 0.5',
    legacy59_to_level: draft,
  }, null, 2) + '\n');

  console.log(`Wrote ${path.relative(ROOT, OUT_MD)}`);
  console.log(`Wrote ${path.relative(ROOT, OUT_JSON)}  (${Object.keys(draft).length} confident rows of ${legacy.length})`);
  console.log('');
  console.log(`  strong candidate:  ${strong}`);
  console.log(`  weak candidate:    ${weak}   <- review these first`);
  console.log(`  no match:          ${none}   <- decide manually`);
}

main().catch(err => { console.error(err); process.exit(1); });
